# .github/labeler.yml - Config for actions/labeler action
# Defines labels based on files modified in a PR

# Label for CI/CD changes
ci/cd:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/*', 'justfile', 'Dockerfile']

# Label for documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file: ['README.md', 'docs/**/*.md', 'docs/**/*', '*.md']

# Label for source code changes
source:
  - changed-files:
      - any-glob-to-any-file: ['src/**/*.ts', 'src/**/*.js', 'src/**/*.json', 'src/**/*.md', 'main.ts']

# Label for configuration changes / patches
patch:
  - changed-files:
      - any-glob-to-any-file: ['LICENSE', 'justfile', 'deno.json', 'deno.lock', '.github/labeler.yml', '.github/settings.yml', '.github/dependabot.yml', '.github/ISSUE_TEMPLATE/*', '.github/CODEOWNERS', '.github/*.yml', '.gitignore', '.gitattributes']

scripts:
  - changed-files:
      - any-glob-to-any-file: ['scripts/**/*']

config:
  - changed-files:
      - any-glob-to-any-file: ['.env', '.env.example', 'deno.json', 'deno.lock', 'biome.json', '.nvmrc', '.pre-commit-config.yaml', '.shellcheckrc', '.gitattributes', '.gitignore', '.vscode/**/*']

meta:
  - changed-files:
      - any-glob-to-any-file: ['LICENSE', 'SECURITY.md', '.github/labeler.yml', '.github/settings.yml', '.github/ISSUE_TEMPLATE/*', '.github/CODEOWNERS', '.github/*.yml']

feature:
 - head-branch: ['^feature', 'feature']

fix:
 - head-branch: ['^fix', 'fix']

ci:
 - head-branch: ['^ci', 'ci']

refactor:
 - head-branch: ['^refactor', 'refactor']
