---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Updated rev for potentially newer hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: &readme_excludes >
          (?x)^(
            README\.md|
            CHANGELOG\.md|
            repomix-output\.xml
          )$
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        exclude: >
          (?x)^(
            src/data/.*
          )$
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-json
        exclude: &json_excludes >
          (?x)^(
            \.vscode/.*\.json|
            deno\.json|
            biome\.json
          )$
      - id: pretty-format-json
        exclude: *json_excludes

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28 # Keep existing or update if needed
    hooks:
      - id: shellcheck
