---
name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the project
title: "[FEATURE] Brief description of the feature"
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: 📝 Feature Description
      description: Provide a clear and concise description of the feature you're proposing.
      placeholder: "Describe what you want to happen..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What's the current limitation or pain point?
      placeholder: "I'm frustrated when... Currently it's difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe how you envision this feature working. Include any implementation ideas or suggestions.
      placeholder: "I would like to see... This could work by..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What other solutions or workarounds have you considered?
      placeholder: "I've tried... Another approach could be..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - "🔥 Critical - Blocking my work"
        - "🟠 High - Would significantly improve my workflow"
        - "🟡 Medium - Nice to have"
        - "🟢 Low - Minor improvement"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: ⚡ Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "🟢 Simple - Small change or addition"
        - "🟡 Medium - Moderate changes required"
        - "🟠 Complex - Significant changes or new components"
        - "🔴 Very Complex - Major architectural changes"
        - "❓ Unknown - Not sure about complexity"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 📋 Additional Context
      description: Add any other context, screenshots, mockups, or examples that might help explain the feature.
      placeholder: "You can attach images by dragging & dropping, selecting, or pasting them."
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: ✅ Acknowledgements
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested before
          required: true
        - label: I understand this is a feature request and not a bug report
          required: true
        - label: I'm willing to help implement this feature if needed
          required: false
        - label: This feature might introduce breaking changes
          required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 📜 Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
